# Generated by Django 4.1.5 on 2023-01-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
